name: automerge

on:
  push:
    branches: [release/*]

concurrency:
  group: automerge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  automerge:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Merge to main
        run: echo 'foo'
